### ISSUE TITLE
Process for obtaining the adb logs?

### ISSUE THREAD

**Issue by dijikul** [jani00/pixel-2-camera-fix#1]
Would you be able to list which steps you performed to get to the actuator errors?  Knowing whether these errors occur on my device would be great help to understand whether the magnet issue is relevant for my problem, when I may be using a not-strong-enough magnet, or placing it in the wrong spot.

I've loaded the SDK and see the adb commands and assume it's related to logcat, but I haven't been able to get my device to connect to the PC I'm using to troubleshoot with.

Thanks in advance!

UPDATE:  Figured it out -- Enabled USB Debugging within Dev Options, which was the piece I was missing for logcat to show data.

Looks similar.  

```08-24 17:44:08.132 11356 16693 E mm-camera: <SENSOR><ERROR> 523: af_actuator_set_params: failed rc -1
08-24 17:44:08.132 11356 16693 E mm-camera: <SENSOR><ERROR> 1110: actuator_process: failed rc -1
08-24 17:44:08.132 11356 16693 E mm-camera: <SENSOR><ERROR> 1056: module_sensor_actuator_init_calibrate: sensor_failure : ACTUATOR_SET_PARAMETERS failed
08-24 17:44:08.132 11356 16693 E mm-camera: <SENSOR><ERROR> 225: module_sensor_offload_init_config: module_sensor_actuator_init_calibrate failed```

**Comment by jani00** [comment]
Yes, looks exactly the same.

**Comment by dijikul** [comment]
It looks like replacement camera modules are about $20USD online and the processes for replacing them is on iFixit via Google.  Question for you though -- does your camera module make a shaking noise as if something loose inside?  Mine's done so for quite some time, without any impact to camera functionality, as others online too report.  
I'm curious if maybe finally the shaking became worse from being dropped or something, ultimately causing the failure.

Another thing I learned is if you hold down the Camera icon on the Launcher, you get an option to take a selfie which launches the camera in forward-facing mode, preventing the crash.

Thanks again for your posting on this.  It definitely helped me.

**Comment by jani00** [comment]
Yes, mine was a $20 module, and it is working perfectly fine. I local guy in my town fixed it for about $15 fee (I live in a somewhat poor country)

Second question: also yes, this new camera also has the rattling noise, That is due to the optical image stabilization (OIS). I believe that the failure was due to overheating, it makes more sense to me. The rattling is somewhat normal. If you watch one of JerryRigEverything videos of a smartphone teardown you will see that cameras with OIS rattle if you move them.

Yes, you can take selfies that way, I used to use that method, but the front camera is really poor quality.

Good luck with your phone!

**Comment by j-e-n-k-s-y** [comment]
Cheers, thanks.  I may try to replace it myself.  Google support directed me to a local company that wants $165 (CAD) to complete the work (including the sensor).

Do you suspect the heat issue to have caused something internal to become disconnected from melting?  My camera stopped working a day or two after having it strapped to the handlebars of an offroad vehicle.  Before it died completely, it would very-occassionaly work, like every couple attempts, progressively getting worse.

Burnt connections makes sense.
