### ISSUE TITLE
Camera module

### ISSUE THREAD

**Issue by gustavokambara** [jani00/pixel-2-camera-fix#2]
Hello!

Unfortunately, I am experiencing this Pixel 2 camera issue for a while. Your information has helped me a lot during my quest to find a solution, so thanks for that.

The magnet trick worked for me during some time, but I am considering replacing the camera module now, as you did.

I didn't find another way to contact you, so I'm opening an issue to ask:

Do you mind sharing the link to the product you bought in AliExpress? There are too many options out there and it would be nice to buy from the same seller, since it already worked in your mobile phone.

Thanks in advance!

**Comment by jani00** [comment]
Hey, happy to hear that I was of any help!

I Also got tired of the magnet trick, so I bought this item from AliExpress: https://www.aliexpress.com/item/32873846118.html
This is exactly the part that I got.

So far it has been working as expected (7-8 months already). No issues and picture quality is the same as the original.

**Comment by gustavokambara** [comment]
Thank you so much for the quick reply and for the link to the product!

Long life to our new camera modules!

Best regards!
